---

- hosts: all
  become: yes
  vars_prompt:
  tasks:
    - name: Install packages
      dnf:
        name:
          - bat
          - htop
          - NetworkManager
          - NetworkManager-tui
          - vim
          - ncdu
          - tldr
          - exa
          - arp-scan
          - wget
          - lynis
    - name: Create secure user
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash }}"
        shell: /bin/bash
        groups:
          - wheel
        state: present
    - name: Set root password
      user:
        name: root
        password: "{{ root_password | password_hash }}"
