---

- hosts: all
  become: yes
  vars_prompt:
  tasks:
    - name: Create secure user
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash }}"
        shell: /bin/bash
        groups:
          - wheel
        state: present
    - name: Set root password
      user:
        name: root
        password: "{{ root_password | password_hash }}"
  roles:
    - base
    - hardening
