---

- name: Create NetworkManager config directory
  file:
    path: /etc/systemd/system/NetworkManager.service.d/
    state: directory
- name: Install NetworkManager service file
  copy:
    src: NetworkManager.override.conf
    dest: /etc/systemd/system/NetworkManager.service.d/override.conf
- name: Reload NetworkManager
  service:
    name: NetworkManager
    state: reloaded

################################################################################
# In accordance with the RedHat Guide on hardening RHEL 9
################################################################################
- name: Update all packages
  dnf:
    name: "*"
    state: latest
- name: Enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
- name: Disable unused services
  service:
    state: stopped
    enabled: no
    # set in vars/main.yml
    name: "{{ item }}"
  loop: "{{ unused_services }}"

# Disabled because I can't get SSH to work with FIPS enabled
# - name: Enable FIPS mode
#   command: fips-mode-setup --enable
# - name: Reboot for FIPS changes
#   reboot:
